language: php

php:
    - 5.3
    - 5.5

env:
    - WP_VERSION=latest WP_MULTISITE=0

services:
    - redis-server

before_script:
    - echo 'extension = "redis.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit
