language: php

php:
    - 5.3
    - 5.5

env:
    - WP_VERSION=latest WP_MULTISITE=0

install:
    - sudo bash bin/install-redis.sh

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit
